retargeting:
  type: DexPilot
  urdf_path: dex-hand/urdf_v2_thumb_in.urdf

  # Target refers to the retargeting target, which is the robot hand
  target_joint_names: [ 'ff_proximal_joint', 'mf_proximal_joint', 'rf_proximal_joint', 'lf_proximal_joint', 'th_joint_2', 'th_joint_1'  ]
  scaling_factor: 0.8
  wrist_link_name: "base_link"
  finger_tip_link_names: [ "thumb_tip",  "index_tip", "middle_tip", "ring_tip", "pinky_tip"]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 1.0
